version: '3.8'

services:
  app:
    build: .
    ports:
      - "3010:3010"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/hitzone
      - NODE_ENV=production
      - PORT=3010
    mem_limit: 1g
    depends_on:
      - mongodb
    restart: unless-stopped

  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data:
